name: Build Check

on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install g++
        run: sudo apt-get install -y g++

      - name: Skip if team lead
        if: github.actor == 'Xenos-10'
        run: echo "✅ Team lead — build check skipped"

      - name: Compile
        if: github.actor != 'Xenos-10'
        run: |
          g++ src/*.cpp -I include -o game
          echo "✅ Compiled successfully"
